COUNTDOWN_NYE_2021 = [
    "Major Lazer",
    "Tiësto",
    "Diplo",
    "Deadmau5",
    "Afrojack",
    "Alan Walker",
    "Flux Pavilion",
    "A-Trak",
    "Showtek",
    "Borgore",
    "RL Grime",
    "Flosstradamus",
    "3LAU",
    "NGHTMRE",
    "Lost Kings",
    "Claptone",
    "TroyBoi",
    "Rezz",
    "Party Favor",
    "Liquid Stranger",
    "KAYZO",
    "AC Slater",
    "Mitis",
    "Manila Killa",
    "G Jones",
    "Wax Motif",
    "Dion Timmer",
    "Lee Foss",
    "Jason Ross",
    "RIOT TEN",
    "Subtronics",
    "4B",
    "Kai Wachi",
    "Dirt Monkey",
    "Boogie T",
    "Kaivon",
    "Matroda",
    "Wuki",
    "William Black",
    "Charlesthefirst",
    "LSDREAM",
    "Zookeper",
    "Of the Trees",
    "Blunts & Blondes",
    "Ardalan",
    "Crystal Skies",
    "SAYMYNAME",
    "SIDEPIECE",
    "Nurko",
    "Chee",
    "Rome in silver",
    "Lil’ Texas",
    "Dack Janiels",
    "SubDocta",
    "Sage Armstrong",
    "Syence",
    "J. Worra",
    "LP Giobbi",
    "Bassrush",
    "Lucati",
    "Effin",
    "Black V Neck",
    "Westend",
    "Corrupt (UK)",
    "ACRAZE",
    "LEVEL UP",
    "NALA",
    "Pauline Herr",
    "Audiotistic",
    "Secret Recipe",
    "CHOMPPA",
    "Tsu Nami",
    "Capozzi",
    "phonon",
    "Luke Andy"
]
